BEGIN;

CREATE TABLE IF NOT EXISTS "FeatureFlags"
(
  "Name" text PRIMARY KEY,
  "Owner" text NOT NULL DEFAULT '',
  "TagsJson" text NOT NULL DEFAULT '[]',
  "RequirementType" integer NOT NULL,
  "Version" integer NOT NULL DEFAULT 1,
  "UpdatedAtUtc" timestamp with time zone NOT NULL,
  "ScheduledAtUtc" timestamp with time zone
);

CREATE TABLE IF NOT EXISTS "FeatureFilters"
(
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" text NOT NULL,
  "FeatureFlagName" text NOT NULL,
  "ParametersJson" text NOT NULL DEFAULT '{}',
  CONSTRAINT "FK_FeatureFilters_FeatureFlags_FeatureFlagName"
    FOREIGN KEY ("FeatureFlagName")
    REFERENCES "FeatureFlags"("Name")
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_FeatureFilters_FeatureFlagName"
  ON "FeatureFilters" ("FeatureFlagName");

CREATE TABLE IF NOT EXISTS "FeatureFlagAuditLogs"
(
  "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FeatureFlagName" text NOT NULL,
  "Action" integer NOT NULL,
  "SnapshotVersion" integer NOT NULL,
  "SnapshotJson" text NOT NULL,
  "ChangedAtUtc" timestamp with time zone NOT NULL,
  "ChangedBy" text NOT NULL
);

CREATE INDEX IF NOT EXISTS "IX_FeatureFlagAuditLogs_FeatureFlagName_Id"
  ON "FeatureFlagAuditLogs" ("FeatureFlagName", "Id");

CREATE TABLE IF NOT EXISTS "FeatureFlagActivityEntries"
(
  "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FeatureFlagName" text NOT NULL,
  "ActivityType" text NOT NULL,
  "Description" text NOT NULL,
  "ChangeType" text,
  "ChangedAtUtc" timestamp with time zone NOT NULL,
  "ChangedBy" text NOT NULL
);

CREATE INDEX IF NOT EXISTS "IX_FeatureFlagActivityEntries_FeatureFlagName_Id"
  ON "FeatureFlagActivityEntries" ("FeatureFlagName", "Id");

CREATE TABLE IF NOT EXISTS "FeatureFlagExperiments"
(
  "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FeatureFlagName" text NOT NULL,
  "BaselineVariant" text NOT NULL,
  "ChallengerVariant" text NOT NULL,
  "BaselineTrafficPercentage" integer NOT NULL,
  "ChallengerTrafficPercentage" integer NOT NULL,
  "ConversionMetricName" text NOT NULL,
  "LatencyMetricName" text NOT NULL,
  "MinimumSampleSize" integer NOT NULL,
  "IsActive" boolean NOT NULL,
  "CreatedAtUtc" timestamp with time zone NOT NULL,
  "UpdatedAtUtc" timestamp with time zone NOT NULL,
  CONSTRAINT "FK_FeatureFlagExperiments_FeatureFlags_FeatureFlagName"
    FOREIGN KEY ("FeatureFlagName")
    REFERENCES "FeatureFlags"("Name")
    ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_FeatureFlagExperiments_FeatureFlagName"
  ON "FeatureFlagExperiments" ("FeatureFlagName");

CREATE TABLE IF NOT EXISTS "FeatureFlagExperimentVariantMetrics"
(
  "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FeatureFlagExperimentId" bigint NOT NULL,
  "Variant" text NOT NULL,
  "SampleSize" bigint NOT NULL,
  "ConversionCount" bigint NOT NULL,
  "ErrorCount" bigint NOT NULL,
  "TotalLatencyMs" double precision NOT NULL,
  CONSTRAINT "FK_FeatureFlagExperimentVariantMetrics_FeatureFlagExperiments_FeatureFlagExperimentId"
    FOREIGN KEY ("FeatureFlagExperimentId")
    REFERENCES "FeatureFlagExperiments"("Id")
    ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_FeatureFlagExperimentVariantMetrics_ExperimentId_Variant"
  ON "FeatureFlagExperimentVariantMetrics" ("FeatureFlagExperimentId", "Variant");

COMMIT;

