BEGIN;

CREATE TABLE IF NOT EXISTS "FeatureFlags"
(
  "Name" text PRIMARY KEY,
  "RequirementType" integer NOT NULL,
  "Version" integer NOT NULL DEFAULT 1,
  "UpdatedAtUtc" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "FeatureFilters"
(
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" text NOT NULL,
  "FeatureFlagName" text NOT NULL,
  "ParametersJson" text NOT NULL DEFAULT '{}',
  CONSTRAINT "FK_FeatureFilters_FeatureFlags_FeatureFlagName"
    FOREIGN KEY ("FeatureFlagName")
    REFERENCES "FeatureFlags"("Name")
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_FeatureFilters_FeatureFlagName"
  ON "FeatureFilters" ("FeatureFlagName");

COMMIT;

