-- PostgreSQL Migration Script
-- Adds new columns and tables for scheduled rollouts and activity feed
-- Version: 1.0
-- Date: 2026-05-26

BEGIN;

-- Add ScheduledAtUtc column to FeatureFlags table
-- If the column already exists, this will fail; you can safely ignore the error
ALTER TABLE IF EXISTS "FeatureFlags" ADD COLUMN IF NOT EXISTS "ScheduledAtUtc" timestamp with time zone;

-- Create FeatureFlagActivityEntries table if it doesn't exist
CREATE TABLE IF NOT EXISTS "FeatureFlagActivityEntries"
(
  "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FeatureFlagName" text NOT NULL,
  "ActivityType" text NOT NULL,
  "Description" text NOT NULL,
  "ChangeType" text,
  "ChangedAtUtc" timestamp with time zone NOT NULL,
  "ChangedBy" text NOT NULL
);

-- Create index if it doesn't exist
CREATE INDEX IF NOT EXISTS "IX_FeatureFlagActivityEntries_FeatureFlagName_Id"
  ON "FeatureFlagActivityEntries" ("FeatureFlagName", "Id");

COMMIT;

